source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "Streams" do
	pod 'MBProgressHUD', '1.0.0'
	pod 'Parse', '1.14.2'
	pod 'ParseUI', '1.2.0'
    pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools', :tag => '2.0.0-beta.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
